name: checks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  TERM: xterm
  REVIVE_FORCE_COLOR: 1

jobs:
  test:
    name: run-testcases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.18', '1.19']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: start services
        run: docker compose up -d
      - name: run testcases
        run: make test2
      - name: benchmark
        run: make bench
      - name: linter
        run: make lint
      - name: vet
        run: make vet


